<script setup lang="ts">
import{computed,onMounted,ref}from'vue';import{useRouter}from'vue-router';import{ElMessage,ElMessageBox}from'element-plus';import{Lightning,Location,Search}from'@element-plus/icons-vue';import{getAllChargingStations,startCharging as startChargingApi}from'@/api/chargingStationsApi';import{useUserStore}from'@/stores/user';
const router=useRouter(),store=useUserStore(),loading=ref(false),stations=ref<any[]>([]),keyword=ref('');const norm=(s:any)=>String(s)==='0'||s==='available';const filtered=computed(()=>stations.value.filter(s=>norm(s.status)&&(!keyword.value||`${s.stationName}${s.location}`.includes(keyword.value))));const load=async()=>{loading.value=true;try{const r:any=await getAllChargingStations();stations.value=Array.isArray(r?.data)?r.data:[]}finally{loading.value=false}};onMounted(load);
const start=async(s:any)=>{const id=store.user?.id;if(!id){router.push('/user-login');return}try{const p=await ElMessageBox.prompt('请输入本次充电时长（分钟）','确认开始充电',{inputValue:'60',inputPattern:/^([1-9]|[1-9]\d|1[0-7]\d|180)$/,inputErrorMessage:'请输入 1—180 分钟'});const d=Number(p.value);await startChargingApi(id,s.stationId,d);ElMessage.success('充电已开始');router.push(`/charging/${s.stationId}?duration=${d}&location=${encodeURIComponent(s.location||'校园充电区')}`)}catch(e){if(e!=='cancel'&&e!=='close')console.error(e)}}
</script>
<template>
  <div class="action-page">
    <header class="page-header action-header">
      <div><p>QUICK CHARGE / READY</p><h1>选择设备，开始充电。</h1><span>仅展示当前可用设备；选择后设置 1—180 分钟充电时长。</span></div>
      <div class="availability"><span><i/>LIVE NETWORK</span><strong>{{filtered.length}}</strong><small>AVAILABLE</small></div>
    </header>
    <main class="stations-main charge-console">
      <section class="console-bar">
        <div class="console-title"><span><Lightning/></span><div><small>DEVICE SELECTOR</small><strong>空闲充电桩</strong></div></div>
        <el-input v-model="keyword" :prefix-icon="Search" clearable placeholder="搜索站点或位置"/>
        <span class="sync-state"><i/> 数据已同步</span>
      </section>
      <section v-loading="loading" class="device-list">
        <div class="device-labels" aria-hidden="true"><span>设备</span><span>位置</span><span>输出</span><span>费率</span><span>操作</span></div>
        <article v-for="(s,index) in filtered" :key="s.stationId">
          <div class="device-name"><span>{{String(index + 1).padStart(2,'0')}}</span><div><i/><h2>{{s.stationName}}</h2></div></div>
          <p><Location/>{{s.location||'校园充电区'}}</p>
          <dl><div><dt>POWER</dt><dd>{{s.powerRating||7}} <small>kW</small></dd></div></dl>
          <dl><div><dt>RATE</dt><dd>¥{{Number(s.pricePerHour||.5).toFixed(2)}} <small>/ h</small></dd></div></dl>
          <button type="button" @click="start(s)">START <Lightning/></button>
        </article>
        <el-empty v-if="!loading&&!filtered.length" description="暂无空闲充电桩"/>
      </section>
      <footer class="console-foot"><span>操作提示</span><p>点击 START 后输入充电时长，系统将立即锁定当前设备并开始计时。</p><b>01 — 180 MIN</b></footer>
    </main>
  </div>
</template>
<style scoped>
.action-page{min-height:calc(100vh - 64px);padding-bottom:64px;background:var(--surface-muted)}.action-header{display:flex;align-items:flex-end;justify-content:space-between;gap:40px;padding-top:58px!important;padding-bottom:36px!important}.action-header p,.action-header h1,.action-header span{margin:0}.action-header p{color:var(--brand);font-size:11px;font-weight:800;letter-spacing:.18em}.action-header h1{max-width:850px;margin:14px 0 15px;font-size:clamp(42px,5.6vw,68px);font-weight:650;line-height:1;letter-spacing:-.06em}.action-header>div>span{color:var(--text-secondary);font-size:14px}.availability{min-width:156px;padding:18px 20px;color:#fff;background:#0a0b0d;border-radius:12px}.availability>span{display:flex;align-items:center;gap:6px;color:#adb1b8;font-size:8px!important;font-weight:800;letter-spacing:.14em}.availability span i{width:6px;height:6px;background:#b8f34a;border-radius:50%;box-shadow:0 0 0 3px rgba(184,243,74,.12)}.availability strong,.availability small{display:block}.availability strong{margin-top:18px;font-size:39px;line-height:.8;letter-spacing:-.05em}.availability small{margin-top:8px;color:#b8f34a;font-size:8px;font-weight:800;letter-spacing:.16em}
.charge-console{background:var(--surface);border:1px solid var(--border-color);border-radius:14px;overflow:hidden}.console-bar{min-height:74px;display:grid;grid-template-columns:1fr minmax(260px,390px) auto;align-items:center;gap:22px;padding:13px 18px;background:#0a0b0d}.console-title{display:flex;align-items:center;gap:12px;color:#fff}.console-title>span{width:38px;height:38px;display:grid;place-items:center;color:#0a0b0d;background:#b8f34a;border-radius:7px}.console-title>span :deep(svg){width:19px}.console-title small,.console-title strong{display:block}.console-title small{color:#80858e;font-size:7px;font-weight:800;letter-spacing:.15em}.console-title strong{margin-top:4px;font-size:13px}.console-bar :deep(.el-input__wrapper){background:#1b1d22!important;border-radius:7px!important;box-shadow:0 0 0 1px #2b2e35 inset!important}.console-bar :deep(.el-input__inner){color:#fff}.sync-state{display:flex;align-items:center;gap:7px;color:#aeb2ba;font-size:9px;font-weight:700}.sync-state i{width:5px;height:5px;background:#b8f34a;border-radius:50%}
.device-list{min-height:260px}.device-labels,.device-list>article{display:grid;grid-template-columns:minmax(240px,1.25fr) minmax(180px,1fr) 110px 120px 112px;align-items:center;gap:18px}.device-labels{min-height:39px;padding:0 22px;color:var(--text-muted);background:#f6f7f8;border-bottom:1px solid var(--border-color);font-size:8px;font-weight:800;letter-spacing:.14em}.device-list>article{min-height:84px;padding:14px 22px;border-bottom:1px solid var(--border-color);transition:background .2s}.device-list>article:hover{background:#f8f9fb}.device-name{display:grid;grid-template-columns:28px 1fr;align-items:center;gap:12px}.device-name>span{color:var(--text-muted);font-size:9px;font-weight:750}.device-name>div{display:flex;align-items:center;gap:10px}.device-name i{width:6px;height:28px;background:#b8f34a;border-radius:2px;box-shadow:0 0 0 1px rgba(32,52,0,.06)}.device-name h2{margin:0;font-size:14px;font-weight:680;letter-spacing:-.02em}.device-list article>p{display:flex;align-items:center;gap:6px;margin:0;color:var(--text-secondary);font-size:11px}.device-list article>p :deep(svg){width:13px;color:var(--text-muted)}.device-list dl{margin:0}.device-list dt{color:var(--text-muted);font-size:7px;font-weight:800;letter-spacing:.13em}.device-list dd{margin:5px 0 0;font-size:13px;font-weight:700;font-variant-numeric:tabular-nums}.device-list dd small{color:var(--text-muted);font-size:8px}.device-list article>button{height:38px;display:flex;align-items:center;justify-content:center;gap:8px;color:#fff;background:var(--brand);border:0;border-radius:7px;font-size:9px;font-weight:850;letter-spacing:.12em;cursor:pointer;transition:background .2s,transform .2s}.device-list article>button:hover{background:var(--text-primary);transform:translateX(2px)}.device-list article>button :deep(svg){width:13px}
.console-foot{min-height:56px;display:grid;grid-template-columns:90px 1fr auto;align-items:center;gap:18px;padding:12px 22px;color:#adb1b8;background:#0a0b0d}.console-foot span{color:#b8f34a;font-size:9px;font-weight:800;letter-spacing:.12em}.console-foot p{margin:0;font-size:10px}.console-foot b{color:#fff;font-size:9px;letter-spacing:.13em}
@media(max-width:900px){.device-labels{display:none}.device-list>article{grid-template-columns:minmax(230px,1fr) 110px 120px}.device-list article>p{grid-column:1;grid-row:2;padding-left:40px}.device-list article>button{grid-column:3;grid-row:2}.device-list>article dl:nth-of-type(2){grid-column:2;grid-row:2}.console-bar{grid-template-columns:1fr 1fr}.sync-state{display:none}}
@media(max-width:680px){.action-header{align-items:flex-start;flex-direction:column}.availability{width:100%;display:grid;grid-template-columns:1fr auto;align-items:end}.availability>span{grid-column:1/-1}.availability strong{margin-top:14px}.availability small{text-align:right}.console-bar{grid-template-columns:1fr}.device-list>article{grid-template-columns:1fr auto;gap:13px;padding:18px}.device-list article>p{grid-column:1/-1;grid-row:2;padding-left:0}.device-list>article dl{grid-row:3}.device-list>article dl:nth-of-type(2){grid-column:2;grid-row:3}.device-list article>button{grid-column:1/-1;grid-row:4}.console-foot{grid-template-columns:1fr}.console-foot b{display:none}}
</style>
